version: '3.7'
services:
  db:
    build: MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Projet_AMT
      - MYSQL_USER=test
      - MYSQL_PASSWORD=Projet_AMT
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOSTS:db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "8888:80"
  payara:
    build: Payara
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "4848:4848"